[project]
name = "auth-system"
version = "0.1.0"
description = "User authentication and management system API"
authors = [
    {name = "OpenHands",email = "openhands@all-hands.dev"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "django (>=5.1.6,<6.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
