[tool.poetry]
name = "auth-system"
version = "0.1.0"
description = "User Authentication and Management System"
authors = ["OpenHands <openhands@all-hands.dev>"]

[tool.poetry.dependencies]
python = "^3.8.1"
django = "^4.2"
djangorestframework = "^3.14.0"
django-allauth = "^0.54.0"
djangorestframework-simplejwt = "^5.2.2"
argon2-cffi = "^21.3.0"
django-ratelimit = "^4.0.0"
django-otp = "^1.1.6"
django-cors-headers = "^4.2.0"
psycopg2-binary = "^2.9.7"
pillow = "^10.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-django = "^4.5.2"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
